apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kl76yo7bs-python 
  janus-idp.io/tekton: kl76yo7bs-python
  backstage.io/kubernetes-id: kl76yo7bs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kl76yo7bs-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml