apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kl76yo7bs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kl76yo7bs-python 
  name: kl76yo7bs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kl76yo7bs-python 
